title: "R3HCS Blog"
description: "Simulation, Unreal, and FEM Devlog"
theme: jekyll-theme-minimal
author: C
url: "https://caryrandazzo.github.io"

custom_links:
  - name: Google
    url: https://www.google.com
  - name: Email
    url: mailto:randazzocary@gmail.com
