title: "R3HCS Blog"
description: "Simulation, Unreal, and FEM Devlog"
theme: jekyll-theme-minimal
author: C
url: "https://caryrandazzo.github.io"

custom_links:
  - name: Portfolio
    url: portfolio
  - name: LinkedIn
    url: https://www.linkedin.com/in/randazzocary/
  - name: Instagram
    url: https://www.instagram.com/p/DIjlEl7uPdP/
  - name: "Email Me"
    url: mailto:randazzocary@gmail.com
